### ISSUE TITLE
tk errors when attempting to run on ubuntu

### ISSUE THREAD

**Issue by vikitech83** [MandyYdnam/Robo_App#19]
Attempting to run roboapp issues tk error:
$ roboapp
initialize batch and user
initialize scripts
initialize command
Traceback (most recent call last):
  File "/home/viksingh/.local/bin/roboapp", line 8, in <module>
    sys.exit(main())
  File "/home/viksingh/.local/lib/python3.8/site-packages/robo_app/__init__.py", line 52, in main
    app = application.Application()
  File "/home/viksingh/.local/lib/python3.8/site-packages/robo_app/application.py", line 20, in __init__
    self.state('zoomed')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2211, in wm_state
    return self.tk.call('wm', 'state', self._w, newstate)
_tkinter.TclError: bad argument "zoomed": must be normal, iconic, or withdrawn

**Comment by MandyYdnam** [comment]
Hi @vikitech83 ,
I have not tested it with ubuntu. But surely I can have a look at it.

**Comment by MandyYdnam** [comment]
@vikitech83 I have made some changes to the tool.
Can you please try the code using following branch?
https://github.com/MandyYdnam/Robo_App/tree/issue/ubuntu
Let me know if you need any help.
